server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: skbtcode
      port: 27017
      host: localhost
      auto-index-creation: true

logging:
  level:
    root: debug


springdoc:
  swagger-ui:
    path: /swagger-api.html
  api-docs:
    path: /api-docs